sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 4
  - 6
  - 8
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
script: npm run $COMMAND
env:
  matrix:
  - COMMAND=test
  - COMMAND=test:browser:cloud
